/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrightBlueElectrical {
  'name' : string,
  'description' : string,
  'rating' : number,
}
export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Review {
  'id' : bigint,
  'serviceName' : string,
  'reviewerName' : string,
  'comment' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export interface ServiceBooking {
  'serviceName' : string,
  'area' : string,
  'name' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'bookService' : ActorMethod<[string, string, string, string], bigint>,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllServiceBookings' : ActorMethod<[], Array<ServiceBooking>>,
  'getBookingsByPhone' : ActorMethod<[string], Array<ServiceBooking>>,
  'getBrightBlueElectrical' : ActorMethod<[], BrightBlueElectrical>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitReview' : ActorMethod<[string, bigint, string, string], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];