/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const EventListing = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const ServiceBooking = IDL.Record({
  'serviceName' : IDL.Text,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const ServiceListing = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const VendorListing = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addEventListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addServiceListing' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addVendorListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'bookService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllEventListings' : IDL.Func([], [IDL.Vec(EventListing)], ['query']),
  'getAllServiceBookings' : IDL.Func([], [IDL.Vec(ServiceBooking)], ['query']),
  'getAllServiceListings' : IDL.Func([], [IDL.Vec(ServiceListing)], ['query']),
  'getAllVendorListings' : IDL.Func([], [IDL.Vec(VendorListing)], ['query']),
  'getBookingsByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ServiceBooking)],
      ['query'],
    ),
  'getBookingsByService' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ServiceBooking)],
      ['query'],
    ),
  'getContactForm' : IDL.Func([IDL.Text], [ContactForm], ['query']),
  'getEventListing' : IDL.Func([IDL.Text], [EventListing], ['query']),
  'getFutureEvents' : IDL.Func([], [IDL.Vec(EventListing)], ['query']),
  'getServiceBooking' : IDL.Func([IDL.Nat], [ServiceBooking], ['query']),
  'getServiceListing' : IDL.Func([IDL.Text], [ServiceListing], ['query']),
  'getVendorListing' : IDL.Func([IDL.Text], [VendorListing], ['query']),
  'getVendorsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(VendorListing)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const EventListing = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const ServiceBooking = IDL.Record({
    'serviceName' : IDL.Text,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const ServiceListing = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const VendorListing = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addEventListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addServiceListing' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addVendorListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'bookService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllEventListings' : IDL.Func([], [IDL.Vec(EventListing)], ['query']),
    'getAllServiceBookings' : IDL.Func(
        [],
        [IDL.Vec(ServiceBooking)],
        ['query'],
      ),
    'getAllServiceListings' : IDL.Func(
        [],
        [IDL.Vec(ServiceListing)],
        ['query'],
      ),
    'getAllVendorListings' : IDL.Func([], [IDL.Vec(VendorListing)], ['query']),
    'getBookingsByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServiceBooking)],
        ['query'],
      ),
    'getBookingsByService' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServiceBooking)],
        ['query'],
      ),
    'getContactForm' : IDL.Func([IDL.Text], [ContactForm], ['query']),
    'getEventListing' : IDL.Func([IDL.Text], [EventListing], ['query']),
    'getFutureEvents' : IDL.Func([], [IDL.Vec(EventListing)], ['query']),
    'getServiceBooking' : IDL.Func([IDL.Nat], [ServiceBooking], ['query']),
    'getServiceListing' : IDL.Func([IDL.Text], [ServiceListing], ['query']),
    'getVendorListing' : IDL.Func([IDL.Text], [VendorListing], ['query']),
    'getVendorsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VendorListing)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };