/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface EventListing {
  'date' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'location' : string,
}
export interface ServiceBooking {
  'serviceName' : string,
  'area' : string,
  'name' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface ServiceListing {
  'icon' : string,
  'name' : string,
  'description' : string,
}
export type Time = bigint;
export interface VendorListing {
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addEventListing' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addServiceListing' : ActorMethod<[string, string, string], undefined>,
  'addVendorListing' : ActorMethod<
    [string, string, string, bigint, string],
    undefined
  >,
  'bookService' : ActorMethod<[string, string, string, string], bigint>,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAllEventListings' : ActorMethod<[], Array<EventListing>>,
  'getAllServiceBookings' : ActorMethod<[], Array<ServiceBooking>>,
  'getAllServiceListings' : ActorMethod<[], Array<ServiceListing>>,
  'getAllVendorListings' : ActorMethod<[], Array<VendorListing>>,
  'getBookingsByPhone' : ActorMethod<[string], Array<ServiceBooking>>,
  'getBookingsByService' : ActorMethod<[string], Array<ServiceBooking>>,
  'getContactForm' : ActorMethod<[string], ContactForm>,
  'getEventListing' : ActorMethod<[string], EventListing>,
  'getFutureEvents' : ActorMethod<[], Array<EventListing>>,
  'getServiceBooking' : ActorMethod<[bigint], ServiceBooking>,
  'getServiceListing' : ActorMethod<[string], ServiceListing>,
  'getVendorListing' : ActorMethod<[string], VendorListing>,
  'getVendorsByCategory' : ActorMethod<[string], Array<VendorListing>>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];