/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ServiceBooking {
    serviceName: string;
    area: string;
    name: string;
    timestamp: Time;
    phone: string;
}
export interface EventListing {
    date: string;
    name: string;
    description: string;
    imageUrl: string;
    location: string;
}
export type Time = bigint;
export interface VendorListing {
    name: string;
    description: string;
    imageUrl: string;
    category: string;
    rating: bigint;
}
export interface ServiceListing {
    icon: string;
    name: string;
    description: string;
}
export interface ContactForm {
    name: string;
    email: string;
    message: string;
}
export interface backendInterface {
    addEventListing(name: string, description: string, date: string, location: string, imageUrl: string): Promise<void>;
    addServiceListing(name: string, description: string, icon: string): Promise<void>;
    addVendorListing(name: string, category: string, description: string, rating: bigint, imageUrl: string): Promise<void>;
    bookService(name: string, phone: string, area: string, serviceName: string): Promise<bigint>;
    getAllContactForms(): Promise<Array<ContactForm>>;
    getAllEventListings(): Promise<Array<EventListing>>;
    getAllServiceBookings(): Promise<Array<ServiceBooking>>;
    getAllServiceListings(): Promise<Array<ServiceListing>>;
    getAllVendorListings(): Promise<Array<VendorListing>>;
    getBookingsByPhone(phone: string): Promise<Array<ServiceBooking>>;
    getBookingsByService(serviceName: string): Promise<Array<ServiceBooking>>;
    getContactForm(formId: string): Promise<ContactForm>;
    getEventListing(name: string): Promise<EventListing>;
    getFutureEvents(): Promise<Array<EventListing>>;
    getServiceBooking(bookingId: bigint): Promise<ServiceBooking>;
    getServiceListing(name: string): Promise<ServiceListing>;
    getVendorListing(name: string): Promise<VendorListing>;
    getVendorsByCategory(category: string): Promise<Array<VendorListing>>;
    submitContactForm(formId: string, name: string, email: string, message: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEventListing(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEventListing(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEventListing(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addServiceListing(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addServiceListing(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServiceListing(arg0, arg1, arg2);
            return result;
        }
    }
    async addVendorListing(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVendorListing(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVendorListing(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async bookService(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllContactForms(): Promise<Array<ContactForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactForms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactForms();
            return result;
        }
    }
    async getAllEventListings(): Promise<Array<EventListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEventListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEventListings();
            return result;
        }
    }
    async getAllServiceBookings(): Promise<Array<ServiceBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServiceBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServiceBookings();
            return result;
        }
    }
    async getAllServiceListings(): Promise<Array<ServiceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServiceListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServiceListings();
            return result;
        }
    }
    async getAllVendorListings(): Promise<Array<VendorListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVendorListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVendorListings();
            return result;
        }
    }
    async getBookingsByPhone(arg0: string): Promise<Array<ServiceBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByPhone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByPhone(arg0);
            return result;
        }
    }
    async getBookingsByService(arg0: string): Promise<Array<ServiceBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByService(arg0);
            return result;
        }
    }
    async getContactForm(arg0: string): Promise<ContactForm> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactForm(arg0);
            return result;
        }
    }
    async getEventListing(arg0: string): Promise<EventListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventListing(arg0);
            return result;
        }
    }
    async getFutureEvents(): Promise<Array<EventListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFutureEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFutureEvents();
            return result;
        }
    }
    async getServiceBooking(arg0: bigint): Promise<ServiceBooking> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceBooking(arg0);
            return result;
        }
    }
    async getServiceListing(arg0: string): Promise<ServiceListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceListing(arg0);
            return result;
        }
    }
    async getVendorListing(arg0: string): Promise<VendorListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorListing(arg0);
            return result;
        }
    }
    async getVendorsByCategory(arg0: string): Promise<Array<VendorListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorsByCategory(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
